name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout in o3smeasures
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Running Ant test script
      run: ant test
